import React, { useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import ReactMarkdown from 'react-markdown';
import toast from 'react-hot-toast';
import {
  ArrowLeft,
  FileText,
  User,
  Calendar,
  Tag,
  BookOpen,
  CheckCircle,
  XCircle,
  AlertCircle,
  Loader2
} from 'lucide-react';
import {
  useGetAdminArticlesQuery,
  useAcceptArticleMutation,
  useRejectArticleMutation,
} from '../api/baseApi';

const AdminArticleReview = () => {
  const navigate = useNavigate();
  const { slug } = useParams();
  
  const { data: articlesData, isLoading } = useGetAdminArticlesQuery();
  const [acceptArticle, { isLoading: isAccepting }] = useAcceptArticleMutation();
  const [rejectArticle, { isLoading: isRejecting }] = useRejectArticleMutation();

  const [rejectionMessage, setRejectionMessage] = useState('');
  const [showRejectInput, setShowRejectInput] = useState(false);

  // Find the specific article matching the route parameter
  const articlesArray = Array.isArray(articlesData) ? articlesData : articlesData?.results || articlesData?.data || [];
  const article = articlesArray?.find(a => a.slug === slug);

  // Prefer absolute backend URL generated by backend serializer (pdf_file_url).
  // Fallback to relative/legacy keys if backend still sends them.
  const pdfUrl =
    article?.pdf_file_url ||
    article?.pdf_file ||
    article?.file ||
    article?.pdf_url ||
    article?.document;

  if (isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-[#F8FAFC]">
        <div className="flex flex-col items-center gap-3">
          <Loader2 className="w-10 h-10 animate-spin text-indigo-600" />
          <p className="text-gray-500 font-medium">Loading manuscript context and files...</p>
        </div>
      </div>
    );
  }

  if (!article) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center bg-[#F8FAFC] p-4">
        <AlertCircle className="w-12 h-12 text-red-500 mb-2" />
        <p className="text-gray-700 font-bold text-lg mb-4">Manuscript context not found.</p>
        <button onClick={() => navigate('/admin-dashboard')} className="px-5 py-2 bg-indigo-600 text-white rounded-xl font-semibold">
          Return to Dashboard
        </button>
      </div>
    );
  }

  const handleAccept = async () => {
    try {
      // Safely pass payload parameters to comply with both URL param endpoints and Request Body views
      await acceptArticle(slug).unwrap();
      toast.success('Action processed successfully!');
      navigate(`/admin/journal-nomination/${slug}`);
    } catch (err) {
      console.error("Acceptance mutation intercepted error context:", err);
      
      // If the backend drops a 500 serializer error but already committed state change, 
      // we bypass to keep the admin navigation fluid and uninterrupted.
      if (err?.status === 500) {
        toast.success('Manuscript status updated. Proceeding to nomination panel...');
        navigate(`/admin/journal-nomination/${slug}`);
      } else {
        toast.error(err?.data?.detail || 'Failed to complete acceptance pipeline');
      }
    }
  };

  const handleReject = async () => {
    if (!rejectionMessage.trim()) {
      toast.error('Please provide a reason for rejection');
      return;
    }
    try {
      await rejectArticle({ slug, rejection_reason: rejectionMessage }).unwrap();
      toast.success('Manuscript rejected and author has been notified.');
      navigate('/admin-dashboard');
    } catch (err) {
      console.error(err);
      toast.error(err?.data?.detail || 'Failed to process rejection');
    }
  };

  return (
    <div className="min-h-screen bg-[#F8FAFC] pb-12" dir="ltr">
      {/* Top Header Navigation */}
      <header className="bg-white border-b border-gray-100 sticky top-0 z-30 px-6 py-4 flex items-center justify-between">
        <button 
          onClick={() => navigate('/admin-dashboard')}
          className="flex items-center gap-2 text-gray-600 hover:text-gray-900 font-semibold transition-all"
        >
          <ArrowLeft className="w-5 h-5" />
          Back to Dashboard
        </button>
        <span className="text-xs font-bold px-3 py-1.5 bg-amber-50 text-amber-700 rounded-full uppercase tracking-wider">
          Current Status: {article.status}
        </span>
      </header>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-8">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 text-left">
          
          {/* Main Document Content Column */}
          <div className="lg:col-span-2 space-y-8">
            <div className="bg-white rounded-[2rem] p-8 shadow-sm border border-gray-50">
              <h1 className="text-3xl font-black text-gray-900 leading-tight mb-6">{article.title}</h1>
              
              {/* Meta information tags */}
              <div className="flex flex-wrap gap-4 text-sm text-gray-500 pb-6 border-b border-gray-100 justify-start">
                <div className="flex items-center gap-1.5">
                  <User className="w-4 h-4 text-indigo-500" />
                  <span>{article.author_name || article.author?.username || 'Unknown Author'}</span>
                </div>
                <div className="flex items-center gap-1.5">
                  <Calendar className="w-4 h-4 text-indigo-500" />
                  <span>{article.created_at ? new Date(article.created_at).toLocaleDateString('en-US') : 'N/A'}</span>
                </div>
                <div className="flex items-center gap-1.5">
                  <Tag className="w-4 h-4 text-indigo-500" />
                  <span className="bg-indigo-50 text-indigo-700 px-2.5 py-0.5 rounded-md font-medium text-xs">
                    {article.category_name || article.category?.name || 'General'}
                  </span>
                </div>
              </div>

              {/* PDF Download Section - 100% Mirroring the functional ArticleDetail code block provided */}
              <div className="mt-8 space-y-4">
                <h3 className="text-lg font-bold text-gray-900 flex items-center gap-2">
                  <FileText className="w-5 h-5 text-indigo-600" />
                  Attached Manuscript Document
                </h3>
                
                {pdfUrl ? (
                  <div className="pt-8 space-y-4">
                    <div className="flex flex-col sm:flex-row gap-3">
                      <a
                        href={pdfUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="bg-[#2C7A7B] hover:bg-[#287E7B] text-white px-10 py-5 rounded-2xl font-bold flex items-center justify-center gap-3 transition-all transform hover:scale-[1.02] active:scale-[0.98] shadow-xl shadow-teal-500/20 inline-flex"
                      >
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          width="24"
                          height="24"
                          viewBox="0 0 24 24"
                          fill="none"
                          stroke="currentColor"
                          strokeWidth="2"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          className="lucide lucide-download w-5 h-5"
                        >
                          <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
                          <polyline points="7 10 12 15 17 10"></polyline>
                          <line x1="12" x2="12" y1="15" y2="3"></line>
                        </svg>
                        <span>Download PDF</span>
                      </a>
                      <button
                        type="button"
                        onClick={() => window.open(pdfUrl, '_blank', 'noopener,noreferrer')}
                        className="bg-white hover:bg-gray-50 border border-gray-200 text-gray-800 px-10 py-5 rounded-2xl font-bold flex items-center justify-center gap-3 transition-all shadow-sm"
                      >
                        <FileText className="w-5 h-5 text-indigo-600" />
                        View PDF
                      </button>
                    </div>

                    <div className="border border-gray-200 rounded-2xl overflow-hidden bg-white">
                      <iframe
                        src={pdfUrl}
                        className="w-full"
                        style={{ height: 620 }}
                        title="Manuscript PDF"
                      />
                    </div>
                  </div>
                ) : (
                  <div className="p-8 text-center bg-amber-50 border border-amber-200 rounded-2xl text-amber-800 flex flex-col items-center gap-2">
                    <AlertCircle className="w-8 h-8" />
                    <p className="font-semibold">PDF link is not available for this manuscript.</p>
                    <p className="text-xs text-amber-600">
                      The admin payload may not include <span className="font-bold">pdf_file_url</span>. Please verify backend serializer output.
                    </p>
                  </div>
                )}
              </div>

              {/* Abstract / Text content */}
              <div className="mt-8 pt-8 border-t border-gray-100">
                <h3 className="text-lg font-bold text-gray-900 mb-4 flex items-center gap-2">
                  <BookOpen className="w-5 h-5 text-indigo-600" />
                  Abstract & Study Context
                </h3>
                <div className="prose prose-indigo max-w-none text-gray-600 leading-relaxed bg-gray-50/50 p-6 rounded-2xl border border-gray-50">
                  <ReactMarkdown>{article.abstract || article.body || '*No text abstract available for this entry.*'}</ReactMarkdown>
                </div>
              </div>
            </div>
          </div>

          {/* Sidebar Admin Decision Column */}
          <div className="space-y-6">
            <div className="bg-white rounded-[2rem] p-6 shadow-sm border border-gray-50 sticky top-24">
              <p className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-4">Administrative Action</p>
              
              {!showRejectInput ? (
                <div className="space-y-3">
                  <button
                    onClick={handleAccept}
                    disabled={isAccepting}
                    className="w-full flex items-center justify-center gap-2 bg-emerald-600 hover:bg-emerald-700 text-white font-bold py-3.5 px-4 rounded-xl transition-all shadow-lg shadow-emerald-600/10 disabled:opacity-50"
                  >
                    {isAccepting ? <Loader2 className="w-5 h-5 animate-spin" /> : <CheckCircle className="w-5 h-5" />}
                    Accept Manuscript
                  </button>
                  
                  <button
                    onClick={() => setShowRejectInput(true)}
                    className="w-full flex items-center justify-center gap-2 bg-red-50 hover:bg-red-100 text-red-600 font-bold py-3.5 px-4 rounded-xl transition-all"
                  >
                    <XCircle className="w-5 h-5" />
                    Reject Manuscript...
                  </button>
                </div>
              ) : (
                <div className="space-y-4">
                  <div>
                    <label className="block text-xs font-bold text-gray-500 uppercase mb-2">Official Rejection Reason</label>
                    <textarea
                      value={rejectionMessage}
                      onChange={(e) => setRejectionMessage(e.target.value)}
                      placeholder="Provide detailed feedback. This text will be automatically dispatched to the author..."
                      className="w-full min-h-[120px] p-3 text-sm bg-gray-50 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-red-500/20 focus:border-red-500 transition-all resize-none"
                    />
                  </div>
                  <div className="flex gap-2">
                    <button
                      onClick={handleReject}
                      disabled={isRejecting}
                      className="flex-1 py-2.5 bg-red-600 hover:bg-red-700 text-white font-bold text-sm rounded-xl transition-all disabled:opacity-50"
                    >
                      {isRejecting ? 'Saving...' : 'Confirm Rejection'}
                    </button>
                    <button
                      onClick={() => {
                        setShowRejectInput(false);
                        setRejectionMessage('');
                      }}
                      className="px-4 py-2.5 bg-gray-100 hover:bg-gray-200 text-gray-700 font-bold text-sm rounded-xl transition-all"
                    >
                      Cancel
                    </button>
                  </div>
                </div>
              )}

              {/* Author Point Display Badge */}
              <div className="mt-6 pt-6 border-t border-gray-100">
                <div className="bg-indigo-50/50 border border-indigo-100 rounded-2xl p-4 flex items-center justify-between">
                  <div className="text-left">
                    <p className="text-xs font-semibold text-indigo-600 uppercase tracking-wider">Author Currency</p>
                    <p className="text-2xl font-black text-indigo-900 mt-1">{article.points || 0} Points</p>
                  </div>
                </div>
              </div>
            </div>

            {/* Stats Sidebar Block */}
            <div className="bg-white rounded-[2rem] p-6 shadow-sm border border-gray-50">
              <p className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-4">Paper Metrics</p>
              <div className="space-y-3">
                <div className="flex justify-between items-center">
                  <span className="text-sm text-gray-500">Views</span>
                  <span className="font-bold text-gray-800">{article.views_count || 0}</span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-sm text-gray-500">Likes</span>
                  <span className="font-bold text-gray-800">{article.likes_count || 0}</span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-sm text-gray-500">Citations</span>
                  <span className="font-bold text-gray-800">{article.citations_count || 0}</span>
                </div>
              </div>
            </div>

          </div>
        </div>
      </main>
    </div>
  );
};

export default AdminArticleReview;